name: Run Node Tests

on:
  push:
    branches: [ main ] # Trigger the workflow on every commit to the main branch.
  pull_request:
    branches: [ main ] # Trigger the workflow on pull requests targeting the main branch.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2 # Step 1: Check out the source code from the repository.

    - name: Use Node.js 20
      uses: actions/setup-node@v2
      with:
        node-version: 20
        cache: 'npm' # Step 2: Use npm caching for faster dependency installs.

    - name: Install Node.js dependencies
      run: npm ci # Step 3: Perform a clean install of Node.js dependencies.

    - name: Run tests
      run: npm test # Step 4: Run tests using the specified Node.js version.
